### ISSUE TITLE
Short Job Keeps Timing Out

### ISSUE THREAD

**Issue by tad3j** [BitWeb/zf2-cron-module#13]
At first for creating this module and making our lives easier.

I've used the config file and modified is as necessary, but for some reason my job newer gets completed. If I set timeout it times out, with error bellow, else it runs forever. If I use string under 1. (console request that I'm trying to get called by cron job) in command line the job gets executed in a few seconds.

I've used a debugger to check if Controller gets reached when called from zf2-cron-module, but it doesn't get, although it works if I call it directly via the job command.

Could anyone suggest why it is timing out, although the action itself only takes a few seconds?

    ======================================================================
    The application has thrown an exception!
    ======================================================================
    BitWeb\CronModule\Exception\TimeoutException
    Jobs: 
    1. C:\wamp\bin\php\php5.4.16\php.exe C:\wamp\www\config\autoload/../../public/index.php email reports weekly
    have taken over 100 seconds to execute.
    ----------------------------------------------------------------------
    C:\wamp\www\vendor\bitweb\zf2-cron-module\src\BitWeb\CronModule\Service\CronService.php:138
    #0 C:\wamp\www\vendor\bitweb\zf2-cron-module\src\BitWeb\CronModule\Service\CronService.php(89): BitWeb\CronModule\Service\CronService->throwErrorIfTimeout()
    #1 C:\wamp\www\vendor\bitweb\zf2-cron-module\src\BitWeb\CronModule\Controller\IndexController.php(24): BitWeb\CronModule\Service\CronService->run()
    #2 C:\wamp\www\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractActionController.php(83): BitWeb\CronModule\Controller\IndexController->indexAction()
    #3 C:\wamp\www\vendor\bitweb\zf2-cron-module\src\BitWeb\CronModule\Controller\IndexController.php(19): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
    #4 [internal function]: BitWeb\CronModule\Controller\IndexController->onDispatch(Object(Zend\Mvc\MvcEvent))
    #5 C:\wamp\www\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
    #6 C:\wamp\www\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #7 C:\wamp\www\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractController.php(116): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #8 C:\wamp\www\vendor\zendframework\zendframework\library\Zend\Mvc\DispatchListener.php(113): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Console\Request), Object(Zend\Console\Response))
    #9 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
    #10 C:\wamp\www\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
    #11 C:\wamp\www\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #12 C:\wamp\www\vendor\zendframework\zendframework\library\Zend\Mvc\Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #13 C:\wamp\www\public\index.php(51): Zend\Mvc\Application->run()
    #14 {main}
    ======================================================================
    Previous Exception(s):

**Comment by tad3j** [comment]
Actually (strangely) it turned out that having debugger on/listening was causing this module to fail/not complete the job. Turning it off solved the problem.
